import './js/mobile-menu';
import './js/categories';
import './js/getPopoularProduct';
import './js/getSearchNews';
import './js/pagination';
import './js/switch';
import './js/search';
// import './js/weather';
// import './js/api/weather-api';
// import './js/markups/weather-markup';